#! /bin/bash

trap "rm -rf images/ && numFile=999999" EXIT SIGINT
mkdir images
magick $1 -coalesce images/out%05d.jpg
numFiles=$(ls images/ | wc -l)
numFile=0;
sleepDuration=$(bc -l <<< "1/$2")
if [ $(echo "$sleepDuration < 0.02" | bc -l) ]; then
        sleepDuration=0.02
fi
echo $sleepDuration
while [ $numFile -lt $numFiles ]; do
        numFile=$(((numFile + 1) % numFiles))
        file=$(printf "images/out%05d.jpg" $numFile)
        feh --bg-scale $file
        sleep $sleepDuration
done
